version: "3"
services:
  app:
    container_name: ms-users
    build: .
    image: cbm3lla/api-lumen-ms-users-dev:1.0 # Etiqueta de la imagen
    volumes:
      - C:/Users/admin/dev/configs/appoinment-magnament/.ms-users:/var/www/html/.env
    ports:
      - "12000:80"
    restart: always
